const excludedCreatures = 
[];
const attacksHardToParse = 
["Attic Whisperer",
"Boggard",
"Daemon, Piscodaemon",
"Dark Stalker",
"Daemon, Purrodaemon",
"Colour Out of Space",
"Devil, Host",
"Disenchanter",
"Div, Akvan",
"Dragon, Primal, Magma, Adult",
"Dragon, Primal, Magma, Ancient",
"Dragon, Primal, Magma, Young",
"Frog, Poison",
"Frog, Giant",
"Ghost",
"Gryph",
"Kami, Toshigami",
"Inevitable, Lhaksharut",
"Kyton, Ostiarius",
"Lamia Matriarch",
"Lizard, Giant Chameleon",
"Magmin",
"Mohrg",
"Nereid",
"Norn",
"Octopus",
"Plasma Ooze",
"Ratling",
"Qlippoth, Chernobue",
"Rusalka",
"Rust Monster",
"Spriggan (Large Size)",
"Stirge",
"Vampiric Mist",
"Urdefhan",
"Wereboar (Hybrid Form)",
"Wererat (Hybrid Form)",
"Wyvaran",
"Zoog"];
export default excludedCreatures;